name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          WORDS: ${{ secrets.ECHO_HELLOWORLD }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NAMEANDIPADDRESS: ${{ secrets.NAMEANDIPADDRESS }}

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install1
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Run install
        run: cd examples/littleweb && yarn install # will run `yarn install` command

      - name: Build production bundle
        run: cd examples/littleweb && yarn build # will run `yarn build` command

      - name: ECHO_HELLOWORLD
        run: echo "$WORDS"

      - name: 删除旧的jar包以及运行脚本
        run: sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $NAMEANDIPADDRESS "cd /root/pubWeb && rm -rf ./*"

      - name: 上传jar包和启动脚本到服务器中
        run: sshpass -p $PASSWORD scp -r -o StrictHostKeyChecking=no ./examples/littleweb/dist $NAMEANDIPADDRESS:/root/pubWeb

      - name: 启动项目
        run: sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $NAMEANDIPADDRESS "nginx -s reload"
